id: copernicus_marine
name: Copernicus Marine Service
description: Credentials for accessing the Copernicus Marine Service API
inputs:
  username:
    label: Username
    help: Your Copernicus Marine Service username
  password:
    label: Password
    help: Your Copernicus Marine Service password
    type: password
